# GitHub Actions workflow: Build & publish Docker image to GitHub Container Registry (ghcr.io)

name: Build & publish container

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/foundryagent-mcp-stub

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Set up Buildx (docker-container driver) so GHA cache works
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      # Log in to the GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker image
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            # Disable automatic branch tags (e.g., "main")
            type=ref,event=branch,enable=false

      # Build and push the image
      - name: Build & push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          provenance: false   # disable provenance image (unknown/unknown)
          sbom: false          # disable SBOM attestation image
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Enable BuildKit cache for faster subsequent builds
          cache-from: type=gha
          cache-to: type=gha,mode=max
